### ISSUE TITLE
Script for model training

### ISSUE THREAD

**Issue by LunaJang** [guanhuankang/Learning-Semantic-Associations-for-Mirror-Detection#1]
Hello!

I really appreciate of your research and the scripts you opened.

I would like to ask if you can get the code you used to learn the model. We want to finetune the model for the dataset we have.

I'd be very happy if you could give me an answer!

**Comment by guanhuankang** [comment]
Thanks!

We have detailed the training setting in Table.2 of the main paper. You can re-train our model from scratch by yourself. For your information, you can find our pretrained semantic side-path and other checkpoints in this link https://drive.google.com/drive/folders/1URH98GqQas3wyCBVgxLZ3wXhDMxhskC_?usp=sharing 

Best,
Huankang GUAN
