### ISSUE TITLE
In the PMD result graph you provided, there seem to be a lot of fuzzy pictures, is the picture provided wrong?

### ISSUE THREAD

**Issue by liu-tianxiang** [guanhuankang/Learning-Semantic-Associations-for-Mirror-Detection#2]
In the PMD result graph you provided, there seem to be a lot of fuzzy pictures, is the picture provided wrong?
![Snipaste_2023-05-03_16-37-22](https://user-images.githubusercontent.com/90261211/235868633-f1a45041-352f-4906-8e3f-8931b8240c58.png)

**Comment by guanhuankang** [comment]
Hi,

The released PMD results are correct. You can obtain possibility maps with normalization. We use default threshold (ie. 0.5) to get the binary maps. Here is a pseudo code:

'''
pred_mask = np.array(Image.open(path_to_mask).convert("L")).astype(float)
pred_mask = pred_mask / pred_mask.max() ## normalize to [0,1], also can represent as possibility map
binary_map = pred_mask > 0.5 ## True means mirror, False means non-mirror
'''

**Comment by liu-tianxiang** [comment]
Thank you for your reply. It has been solved
