### ISSUE TITLE
The RGBD_mirror dataset has two results, which is the final result?

### ISSUE THREAD

**Issue by liu-tianxiang** [guanhuankang/Learning-Semantic-Associations-for-Mirror-Detection#3]
The RGBD_mirror dataset has two results, which is the final result?   
test_on_rgbd or test_on_rgbd_wo_dep_map

**Comment by guanhuankang** [comment]
Hi, as shown in Table.4 in main paper, we release the evaluation results for two cases:
1. using depth maps (i.e. test_on_rgbd) during both training and inference
2. only use the RGB images without the need of depth map (i.e test_on_rgbd_wo_dep_map)

Thus, for a fair comparison, if you use the depth information in your case, you should refer to test_on_rgbd (IOU is 78.43 in Table.4). If you do not rely on depth information, you can adopt the sub-optimal one (IOU is 74.99 in Table.4). 

Thanks!
