### ISSUE TITLE
关于权重和结果

### ISSUE THREAD

**Issue by zkjkak** [guanhuankang/Learning-Semantic-Associations-for-Mirror-Detection#4]
康博士，您好，在您公布的模型权重和测试结果的google网盘的链接都已经失效了，不知道能否重新提供一下？非常感谢您的帮助

**Comment by guanhuankang** [comment]
Thank you for your attention on our work! The link is accessible, and you can find the checkpoints and other resources via the link we provided (https://drive.google.com/drive/folders/1URH98GqQas3wyCBVgxLZ3wXhDMxhskC_?usp=sharing).

**Comment by zkjkak** [comment]
Thank you very much for your help
